# ZJNUCTF 202008 Web Sign in
version: "2"

services:

  web:
    build: .
    image: zjnuctf/unserialize_it
    environment:
      - FLAG=flag{test_flag}
    restart: always
    ports:
      - "0.0.0.0:9015:80"
