# ZJNUCTF 202008 Web Sign in
version: "2"

services:

  web4:
    build: .
    image: zjnuctf/xs_web4_l_love_sql
    environment:
      - FLAG=flag{test_flag}
    restart: always
    ports:
      - "0.0.0.0:9014:80"
    container_name: zjnuctf_xs_web4_l_love_sql
    tty: true
    
