# ZJNUCTF 202008 Web Sign in
version: "2"

services:

  web3:
    build: .
    image: zjnuctf/xs_web3_easy_upload
    environment:
      - FLAG=flag{test_flag}
    restart: always
    ports:
      - "0.0.0.0:9013:80"
    container_name: zjnuctf_xs_web3_easy_upload
    tty: true
    command: /bin/bash