# ZJNUCTF 202008 Web Sign in
version: "2"

services:

  web2:
    build: .
    image: zjnuctf/xs_web2_easy_md5
    environment:
      - FLAG=flag{test_flag}
    restart: always
    ports:
      - "0.0.0.0:9012:80"
    container_name: zjnuctf_xs_web2_easy_md5
    tty: true
    command: /bin/sh